FROM gradle:7.6.1-jdk11

RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*

RUN mkdir /home/app
WORKDIR /home/app
COPY . /home/app

RUN pip install pipenv
RUN pipenv install 

#specifying the chromedriver location
ENV PATH="/home/app/chromedriver-win64:$PATH"

CMD ["./gradlew", "runAllTests"]